sudo: required
services:
    - docker

before_install:
    - docker build -t vinothkumar1selvaraj/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vinothkumar1selvaraj/react-test npm test

after_success:
    - docker build -t vinothkumar1selvaraj/multi-client:latest ./client
    - docker build -t vinothkumar1selvaraj/multi-nginx:latest ./nginx
    - docker build -t vinothkumar1selvaraj/multi-server:latest ./server
    - docker build -t vinothkumar1selvaraj/multi-worker:latest ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
    - docker push vinothkumar1selvaraj/multi-client:latest
    - docker push vinothkumar1selvaraj/multi-nginx:latest
    - docker push vinothkumar1selvaraj/multi-server:latest
    - docker push vinothkumar1selvaraj/multi-worker:latest

deploy:
    edge: true
    provide: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-943722292289
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
